#if !canImport(ObjectiveC)
import XCTest

extension Test {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__Test = [
    ("testTrivial", testTrivial),
  ]
}

public func __allTests() -> [XCTestCaseEntry] {
  [
    testCase(Test.__allTests__Test),
  ]
}
#endif
